### ISSUE TITLE
cannot run file and details ask

### ISSUE THREAD

**Issue by DirtyDrake666** [lyc8503/NJUUtils#1]
请问出现 API Error: 参数错误 怎么办？是因为还未开始吗？以及别人使用您的程序时候应该更改哪些字段？

**Comment by lyc8503** [comment]
抱歉，不提供相关的指导，而且您问题描述的也不是很清楚，我完全不知道发生了什么... （我甚至不知道你运行的是哪个脚本...）

每个程序需要更改的字段通常是开头的一些变量

但有些代码可能年久失修，服务器接口更改也会导致无法使用，我发布前没有测试过，~~所以说是仅供学习参考~~

**Comment by DirtyDrake666** [comment]
啊我说的是您几天前更新的跑步的那个 python 文件！我运行的时候显示API异常，我只想知道那个 api 是否不可用

**Comment by lyc8503** [comment]
上上个学期是可以用的，GitHub 显示的时间是两天前上传，并不代表我是两天前写的

已经过了快一年了，能不能用未知，并且建议你先完整理解一下代码，~~直接盲目使用我的数据上传被学校发现概不负责~~

直接用虚拟定位应该比调这个代码容易（
